Update Russian translation to 2021-05-01
thewca/wca-regulations-translations pull request #103
Opened 2021-05-03 05:50 UTC by TimWCA

Update Russian translations of WCA Regulations and Guidelines to ver. 2021-05-01.

2021-05-07 00:20 UTC, hanwu85 commented on russian/wca-guidelines.md
> +- 9t+) [ОБЪЯСНЕНИЕ] Из-за [9t1](regulations:regulain:9t1) и [9t2](regulations:regulain:9t2) раунды могут выглядеть как несоответствующие [9p1](regulations:regulation:9p1), [9m1](regulations:regulatio
```suggestion
- 9t+) [ОБЪЯСНЕНИЕ] Из-за [9t1](regulations:regulation:9t1) и [9t2](regulations:regulation:9t2) раунды могут выглядеть как несоответствующие [9p1](regulations:regulation:9p1), [9m1](regulations:regulation:9m1), [9m2](regulations:regulation:9m2) или [9m3](regulations:regulation:9m3). Однако внесение изменений для соответствия этим правилам затронет невиновных участников, поэтому результаты должны остаться прежними.
```

2021-05-07 00:21 UTC, hanwu85 commented on russian/wca-guidelines.md
> +- 9t++) [ДОПОЛНЕНИЕ] Если изменения результатов происходят в течении соревнований, это правило также должно быть применено. В этом случае [9t1](regulations:regulain:9t1), [9t2](regulations:regulain:9
typo from the original version.
```suggestion
- 9t++) [ДОПОЛНЕНИЕ] Если изменения результатов происходят в течении соревнований, это правило также должно быть применено. В этом случае [9t1](regulations:regulation:9t1), [9t2](regulations:regulation:9t2) и [9t3](regulations:regulation:9t3) также должны быть соблюдены на усмотрение Делегата WCA.
```

2021-05-07 02:59 UTC, TimWCA commented on russian/wca-guidelines.md
> +- 9t++) [ДОПОЛНЕНИЕ] Если изменения результатов происходят в течении соревнований, это правило также должно быть применено. В этом случае [9t1](regulations:regulain:9t1), [9t2](regulations:regulain:9
Thank you :)

2021-05-07 02:59 UTC, TimWCA commented on russian/wca-guidelines.md
> +- 9t+) [ОБЪЯСНЕНИЕ] Из-за [9t1](regulations:regulain:9t1) и [9t2](regulations:regulain:9t2) раунды могут выглядеть как несоответствующие [9p1](regulations:regulation:9p1), [9m1](regulations:regulatio
:)

2021-05-23 12:15 UTC, AlexKatyukov requested changes
Some not critical comments to Timofei

2021-05-23 12:15 UTC, AlexKatyukov commented on russian/wca-guidelines.md
> +- 9t+) [ОБЪЯСНЕНИЕ] Из-за [9t1](regulations:regulation:9t1) и [9t2](regulations:regulation:9t2) раунды могут выглядеть как несоответствующие [9p1](regulations:regulation:9p1), [9m1](regulations:regul
Hi! This is a review that Timofei asked me to do :) It's in Russian (that's logic)

Мне не очень нравится слово «невиновных». Оно отражает смысл, но какое-то оно странное в данном контексте.

2021-05-23 12:15 UTC, AlexKatyukov commented on russian/wca-guidelines.md
> +- 9t++) [ДОПОЛНЕНИЕ] Если изменения результатов происходят в течении соревнований, это правило также должно быть применено. В этом случае [9t1](regulations:regulation:9t1), [9t2](regulations:regulati
В течени**е**

2021-05-23 12:15 UTC, AlexKatyukov commented on russian/wca-regulations.md
> +    - E3f) Инструменты для удаление пометок (принесённый с собой), такие как корректирующая жидкость, корректирующая лента или ластики.
Удалени**я**

2021-05-23 12:15 UTC, AlexKatyukov commented on russian/wca-regulations.md
> +    - E3f) Инструменты для удаление пометок (принесённый с собой), такие как корректирующая жидкость, корректирующая лента или ластики.
И, наверное, принесённы**е**

2021-05-23 22:07 UTC, Ivan-Brigidano commented
We are still having some software issues with Travis :/   The issues are not related to the PR but to Travis itself. The WST and the WRC are working to solve them ASAP.
Other than this, please tell us when the PR is ready so that we can merge it.

2021-05-24 05:35 UTC, TimWCA commented
I think, it is ready to merge :)

2021-05-26 02:31 UTC, TimWCA commented
> We are still having some software issues with Travis :/ The issues are not related to the PR but to Travis itself. The WST and the WRC are working to solve them ASAP.
> Other than this, please tell us when the PR is ready so that we can merge it.

2021-05-26 02:34 UTC, TimWCA commented
I'm sorry, I accidentally closed this PR :) I reopened it.

2021-07-08 16:56 UTC, Ivan-Brigidano approved these changes

2021-08-10 22:09 UTC, merged