adding polish translation
thewca/wca-regulations-translations pull request #170
Opened 2024-09-12 21:10 UTC by Brzana

If there is anything wrong, contact me through mail attatched to my wca profile

2024-09-17 12:30 UTC, Nanush7 requested changes

2024-09-17 12:30 UTC, Nanush7 commented on polish/README.md
> +the official [World Cube Association Competition Regulations](http://worldcubeassociation.org/regulations/) repository.
```suggestion
the official [World Cube Association Competition Regulations](https://www.worldcubeassociation.org/regulations/) repository.
```

2024-09-17 12:30 UTC, Nanush7 commented on polish/metadata.json
> +  "version": "2024-09-12",
```suggestion
  "version": "2024-01-01",
```

2024-11-30 15:10 UTC, Nanush7 commented
@Brzana Would you please translate the following?
- The name of the Polish language.
- "Regulations".
- "Guidelines".
- "wca-regulations-and-guidelines".

Thank you!

2024-12-02 18:52 UTC, Brzana commented
@Nanush7 
1) Polski
2) Regulamin
3) Wytyczne
4) wca-regulamin-i-wytyczne

2024-12-03 18:35 UTC, Nanush7 commented
Thank you! Is the translation ready to be merged? What's the current status of the review?

2024-12-04 19:23 UTC, poiuytre121 commented
Hi,
I believe we can merge this while we will work on 2025 updates and wording upgrades in the meantime.

Przemysław Rogalski

2024-12-04 20:29 UTC, Nanush7 approved these changes
Sounds good! We need to deploy the new version of the regulations compiler before we can merge this.

2025-01-05 22:32 UTC, Nanush7 commented
I'll merge this to the `fix-polish` branch so I can fix the errors raised by the wrc compiler. I'll then merge it to main.
```
Error: trailing whitespace at line 44 in text '- 1c) Delegat WCA jest odpowiedzialny za zapewnienie przestrzegania regulacji WCA oraz stosownych wytycznych lub wymagań WCA. Delegat WCA może wyznaczyć innego członka zespołu organizacyjnego do pełnienia konkretnego obowiązku w jego imieniu, ale ostatecznie ponosi odpowiedzialność za sposób wykonywania tych obowiązków  '
Illegal character ' ' at line 43
Illegal character ' ' at line 43
Illegal character ' ' at line 43
Error: trailing whitespace at line 83 in text '- 2i) Podczas układania, zawodnik nie może używać urządzeń dźwiękowych ani elektronicznych (np. telefon komórkowy, odtwarzacz MP3, dyktafon, dodatkowe oświetlenie) oprócz timera lub stopera. '
Illegal character ' ' at line 82
Illegal character ' ' at line 82
Illegal character ' ' at line 82
Error: trailing whitespace at line 90 in text '    - 2i4) Zawodnik powinien wyciszyć telefon żeby uniknąć rozpraszania innych zawodników. '
Illegal character ' ' at line 89
Error: trailing whitespace at line 91 in text '        - 2j1a)  Jeśli zawodnik przystąpił już do próby danej konkurencji przed zostaniem zdyskwalifikowanym, pozostałe wyniki zostają odnotowane jako DNF. Jeżeli zawodnik nie rozpoczął prób (tj. nie posiada wyników lub posiada wynik DNS) żadne wyniki nie zostają przypisane. '
Illegal character ' ' at line 90
Illegal character ' ' at line 90
Illegal character ' ' at line 90
Error: trailing whitespace at line 127 in text '    - 3h1) Kostki z wybrzuszonymi ścianami są dozwolone. '
Illegal character ' ' at line 126
Illegal character ' ' at line 126
Illegal character ' ' at line 126
Error: trailing whitespace at line 173 in text '    - 4d4) Zegar jest mieszany, zaczynając od dowolnej strony z przodu, a godzina 12 jest skierowana do góry. '
Illegal character ' ' at line 172
Illegal character ' ' at line 172
Illegal character ' ' at line 172
Error: trailing whitespace at line 234 in text '        - 9b4b) Formaty cutoff dla tej konkurencji: " Najlepszy z 1" faza cutoff dla "Najlepszy z 2" lub "Najlepszy z X" (gdzie X to 1 lub 2) faza cutoff dla "Średnia z 3". '
Illegal character ' ' at line 233
Illegal character ' ' at line 233
Illegal character ' ' at line 233
Error: trailing whitespace at line 256 in text '- 9g) Runda kombinowana to runda z fazą cutoff " Najlepszy z X" i wymogiem cutoff (np. "Najlepszy z 2" z wymogiem cutoff ściśle lepszym niż 2 minuty). Jeśli zawodnik spełni wymóg cutoff w co najmniej jednej ze swoich prób fazy cutoff, kwalifikuje się do pozostałych prób. Próby z fazy cutoff liczą się do pełnego formatu rundy. '
Illegal character ' ' at line 255
Error: trailing whitespace at line 277 in text '- 9u) Zawody uznaje się za zakończone, jeśli spełnione są wszystkie poniższe warunki: '
Illegal character ' ' at line 276
Illegal character ' ' at line 276
Illegal character ' ' at line 276
Error: trailing whitespace at line 312 in text '    - 11e2) Jeśli zawodnikowi zostanie przyznana dodatkowa próba, powinna ona zostać wykonana zaraz po próbie, która ją spowodowała i musi zastąpić pierwotną regularnie numerowaną próbę. '
Illegal character ' ' at line 311
Illegal character ' ' at line 311
Illegal character ' ' at line 311
Error: trailing whitespace at line 354 in text '    - 12g1) Łamigłówkę trzymamy tak aby na górze była godzina 12 '
Illegal character ' ' at line 353
Illegal character ' ' at line 353
Illegal character ' ' at line 353
Error: trailing whitespace at line 369 in text '        - A1a2) W przypadku konkurencji innych niż 3x3x3 Fewest Moves i 3x3x3 Multi-Blind, zespół organizacyjny może określić łączny limit czasu. Łączny limit czasu musi odnosić się do wszystkich prób w jednej rundzie (np. 3 próby z łącznym limitem czasu wynoszącym 20 minut) lub do wszystkich prób w kombinacji rund dla różnych konkurencji. W takim przypadku limit czasowy dla konkretnej próby to limit czasowy lub łączny limit czasowy pomniejszony o łączny czas w innych próbach wliczanych do limitu czasowego do tej pory (zob. [Punkt A1a5](regulations:regulation:A1a5)), w zależności od tego, który z nich jest niższy. Jeśli runda ma obowiązujący łączny limit czasu, musi mieć co najwyżej jeden. '
Illegal character ' ' at line 390
Illegal character ' ' at line 390
Illegal character ' ' at line 390
Illegal character ' ' at line 390
Illegal character ' ' at line 390
Illegal character ' ' at line 390
Illegal character ' ' at line 390
Illegal character ' ' at line 390
Error: trailing whitespace at line 410 in text '- A5) Podczas ułożenia: '
Illegal character ' ' at line 409
Illegal character ' ' at line 409
Illegal character ' ' at line 409
Error: trailing whitespace at line 414 in text '    - A6a) Zawodnik wypuszcza łamigłówkę przed zatrzymaniem rozwiązywania i zatrzymuje rozwiązywanie poprzez zatrzymanie stopera. Jeśli używany jest stoper, sędzia zatrzymuje stoper, gdy tylko zawodnik to zrobi. '
Illegal character ' ' at line 413
Illegal character ' ' at line 413
Illegal character ' ' at line 413
Error: trailing whitespace at line 417 in text '    - A6c) Zawodnik musi całkowicie zwolnić łamigłówkę przed zatrzymaniem stopera. Kara: dyskwalifikacja próby (DNF). Wyjątek: Jeśli po zatrzymaniu stopera, a przed zwolnieniem łamigłówki, nie zastosowano żadnego ruchu lub jakiejkolwiek zmiany w ustawieniu, zamiast tego może zostać przyznana kara czasowa (+2 sekundy), według uznania sędziego. '
Illegal character ' ' at line 416
Illegal character ' ' at line 416
Illegal character ' ' at line 416
Error: trailing whitespace at line 418 in text '    - A6e) Po zatrzymaniu timera zawodnik nie może dotykać łamigłówki, wykonywać nią ruchów ani dokonywać żadnych zmian w jej ułożeniu, dopóki sędzia nie sprawdzi łamigłówki. '
Error: trailing whitespace at line 427 in text '        - A7a1) Sędzia powinien wskazać zawodnikowi, że łamigłówka została rozwiązana lub że zostanie nałożona kara. '
Illegal character ' ' at line 426
Illegal character ' ' at line 426
Illegal character ' ' at line 426
Error: trailing whitespace at line 459 in text '        - B4a1) Dopóki zawodnik nie wykona pierwszego ruchu na łamigłówce, może zdjąć opaskę, aby powrócić do fazy zapamiętywania. '
Illegal character ' ' at line 458
Illegal character ' ' at line 458
Illegal character ' ' at line 458
Error: trailing whitespace at line 466 in text '        - B5a1) Jeśli oprócz timera Stackmat używany jest stoper, sędzia zatrzymuje stoper, gdy tylko zawodnik zatrzyma rozwiązanie. '
Illegal character ' ' at line 465
Illegal character ' ' at line 465
Illegal character ' ' at line 465
Error: trailing whitespace at line 485 in text '        - E2a1) Przed rozpoczęciem próby zawodnik nie może pisać na żadnym papierze przeznaczonym do próby. Wyjątek: zawodnik może napisać informacje identyfikujące próbę (zob. [Punkt E2c1](regulations:regulation:E2c1)). Jeśli napisze te informacje na papierze zawierającym sekwencję mieszającą, musi pisać tylko na stronie bez sekwencji mieszającej przed rozpoczęciem próby. Kara za napisanie czegokolwiek innego niż informacje identyfikujące próbę: dyskwalifikacja próby (DNF). '
Illegal character ' ' at line 484
Illegal character ' ' at line 484
Illegal character ' ' at line 484
Error: trailing whitespace at line 487 in text '    - E2c) Po upływie 60 minut każdy zawodnik musi przedłożyć sędziemu pojedynczą kartkę papieru z zapisanym rozwiązaniem i informacjami umożliwiającymi identyfikację próby. '
Error: trailing whitespace at line 487 in text '       - E2c1) Informacje umożliwiające identyfikację próby to: imię i nazwisko zawodnika, identyfikator WCA ID lub identyfikator zarejestrowanego uczestnika zawodów (co najmniej jeden, opcjonalnie kilka) oraz opcjonalnie nazwa zawodów, runda lub numer próby. Kara za przedłożenie rozwiązania bez imienia i nazwiska, identyfikatora WCA lub identyfikatora zarejestrowanego zawodnika: dyskwalifikacja próby (DNF). '
Error: trailing whitespace  [...]

2025-01-05 22:33 UTC, merged